### ISSUE TITLE
Checkbox and Radio?

### ISSUE THREAD

**Issue by gthomas-appfolio** [vatesfr/react-bootstrap#5]
Curious why Checkboxes and Radios are missing from this fork?  
https://react-bootstrap.github.io/components.html#forms-controls

**Comment by julien-f** [comment]
This fork is far from up-to-date, we've just made a few changes for a project using Bootstrap 4, and nobody else invested any effort in maintaining this.

Anyway, i think the upstream repository will now start to work on Bootstrap 4 as well so we should be covered :)

Anyway, if ou need it PRs, are always welcome here!

**Comment by gthomas-appfolio** [comment]
Cool, no problem, thanks for the update!
