### ISSUE TITLE
Classnames are changed and CSS doesn't apply

### ISSUE THREAD

**Issue by mv8ang** [vatesfr/react-bootstrap#6]
Some elements in react-bootstrap-4 have been given classnames different the original Bootstrap ones, and the changes don't reflect the css. For example, .popover-top in the css should be applied to .popover.top, .popover-arrow should be applied to .arrow, etc.

I ended up copy/pasting the Bootstrap classes in my own css and changing the classnames.

Is this something overlooked, or am I doing it wrong?

**Comment by julien-f** [comment]
This fork is very much incomplete, we have just changed what we needed, feel free to improve it if needed.
